-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgni0bygbhz4oPB4sy
y/2Gjp0PstPC/cu0b7NB/kXGFOugCgYIKoZIzj0DAQehRANCAASuhEG8+HyzUwdD
okGnYWMftv77MuEdfPnCzgLhujihk+2twTBI/+KuSQBRtCte0FB6icWDpzrVSfTa
IdFal8hK
-----END PRIVATE KEY-----