# Podfile for Novia - Lynx.js iOS App

platform :ios, '16.0'

target 'Novia' do
  use_frameworks!
  
  # Lynx.js framework - check latest version at https://github.com/bytedance/lynx-native
  pod 'lynx', '~> 3.4.1'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
